// GENERATED BY `dart run content_builder:build`. DO NOT EDIT.
//
// The extraction gate compares [kContentBuildDate] against
// `app_meta.content_build_date` in `user.db`. Both are already in hand: this
// one is compiled into the binary, and that one is a single indexed row in a
// file every screen opens anyway.
//
// SPEC.md §7.4 records why the obvious alternative is wrong. Reading the build
// date out of the shipped database means opening it, which means decompressing
// ten megabytes to disk — the entire job the check exists to skip. The naive
// design therefore re-extracts on every launch, and pays the worst possible
// cost: every time, on the cold-start path, for a comparison of twenty bytes.
library;

/// `content_meta.build_date` of the payload this binary ships with.
const String kContentBuildDate = '2026-08-14';

/// `SPEC.md` §7.1's schema version, as the builder wrote it.
const int kContentSchemaVersion = 1;

/// The UNCOMPRESSED byte count. The determinate progress bar's denominator.
const int kContentBuildBytes = 188416;

/// The UNCOMPRESSED sha256, verified after decompression and before the rename.
const String kContentBuildSha256 =
    'ac31167757fd2057ceb621d992edb2273fb871e7037ecdd83e8f05d9437f461f';
