#!/usr/bin/env python3
"""Diff the resolved dependency graph against the checked-in allowlist.

SPEC.md §14 static block, bullet 1. The contract is EDGE-level, not
package-level: `http` may be reached from exactly `printing` and `flutter_svg`,
`url_launcher_platform_interface` from exactly `share_plus`, and a third edge or
any direct `http` fails.

§5.3 records why. The first draft claimed "no HTTP client is linked" and that
was false — both `printing` and `flutter_svg` declare `http`, and both are on
the required stack. So the honest guarantee is not that `http` is absent but
that it has exactly two named parents, each with a grep-banned entry point. A
gate that cannot express WHICH PARENT cannot express the guarantee, which is why
`dependency-hygiene`'s name-keyed ALLOW set is not enough on its own: allowing
`http` by name makes every future parent acceptable forever.

Usage:
    dart pub deps --json | check_dependency_allowlist.py --allowlist-dir DIR
    check_dependency_allowlist.py --deps FILE --allowlist-dir DIR
    dart pub deps --json | check_dependency_allowlist.py --write

Exit codes: 0 clean · 1 a difference · 2 unusable input (never 0 on a graph it
could not walk — a silent parse failure is a green build over nothing).
"""

from __future__ import annotations

import argparse
import json
import os
import sys

# The two names SPEC.md §14 governs. Watched unconditionally so that deleting a
# line from transitive_edges.txt cannot quietly stop them being checked.
ALWAYS_WATCHED = ("http", "url_launcher_platform_interface")

DIRECT_HEADER = """\
# Generated by tools/gates/check_dependency_allowlist.py --write. Never hand-edited.
#
# One line per `<member> <section> <package>`. This is the set a human reviews in
# the PR diff when a dependency changes — SPEC.md §14, E01/T04. A hand-kept list
# diverges from pubspec.yaml at the first `dart pub add`, after which the gate
# compares two documents and neither describes the app.
"""

EDGES_HEADER = """\
# The transitive-edge exceptions from SPEC.md §14, one line per `<package> <- <parent>`.
#
# `printing` declares http for PdfGoogleFonts and `flutter_svg` declares it for
# SvgPicture.network; both entry points are grep-banned by
# catchlaw-offline-guarantee. `share_plus` is the only sanctioned path to
# url_launcher_platform_interface.
#
# The three lines below are ACTIVE from this commit even though printing and
# share_plus arrive in E17 and flutter_svg in E08. A recorded edge whose package
# is not in the shipping set is simply not checked, so the lines are inert until
# the package lands — and stating the contract now is what lets E01 prove the
# exception instead of discovering it three epics later.
"""


def die(msg: str) -> None:
    print(f"check_dependency_allowlist: {msg}", file=sys.stderr)
    sys.exit(2)


def load_deps(path: str | None) -> dict:
    try:
        raw = sys.stdin.read() if path is None else open(path, encoding="utf-8").read()
    except OSError as e:
        die(f"could not read the dependency JSON: {e}")
    try:
        doc = json.loads(raw)
    except json.JSONDecodeError as e:
        die(f"could not parse the dependency JSON ({e}). Refusing to report success "
            f"over a graph that was never walked.")
    if not isinstance(doc, dict) or "packages" not in doc:
        die("the dependency JSON has no `packages` key — `dart pub deps --json` "
            "changed shape, and this gate would otherwise walk an empty graph.")
    return doc


def read_allowlist(path: str) -> list[str]:
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as fh:
        return [ln.strip() for ln in fh
                if ln.strip() and not ln.lstrip().startswith("#")]


def member_dirs(workspace_root: str) -> dict[str, str]:
    """Map a member's package name to its workspace-relative directory."""
    try:
        import yaml
    except ImportError:  # pragma: no cover - PyYAML ships on the runner
        die("PyYAML is required to read the member pubspecs")
    root_pubspec = os.path.join(workspace_root, "pubspec.yaml")
    if not os.path.exists(root_pubspec):
        return {}
    with open(root_pubspec, encoding="utf-8") as fh:
        root = yaml.safe_load(fh) or {}
    out: dict[str, str] = {}
    for d in root.get("workspace", []) or []:
        p = os.path.join(workspace_root, d, "pubspec.yaml")
        if not os.path.exists(p):
            continue
        with open(p, encoding="utf-8") as fh:
            spec = yaml.safe_load(fh) or {}
        if spec.get("name"):
            out[spec["name"]] = d
    return out


def sections_from_pubspec(workspace_root: str, member_dir: str) -> dict[str, list[str]]:
    import yaml
    with open(os.path.join(workspace_root, member_dir, "pubspec.yaml"),
              encoding="utf-8") as fh:
        spec = yaml.safe_load(fh) or {}
    return {
        "dependencies": sorted((spec.get("dependencies") or {}).keys()),
        "dev_dependencies": sorted((spec.get("dev_dependencies") or {}).keys()),
    }


def closure(seeds: set[str], deps: dict[str, list[str]]) -> set[str]:
    seen: set[str] = set()
    stack = list(seeds)
    while stack:
        n = stack.pop()
        if n in seen:
            continue
        seen.add(n)
        stack.extend(deps.get(n, []))
    return seen


def analyse(doc: dict, workspace_root: str):
    """Return (direct_lines, ships, dev_only, parents).

    Handles the two shapes `dart pub deps --json` actually emits. In a pub
    WORKSPACE every member comes back as `kind: root` with no direct/dev split at
    all, so the sections are read from each member's own pubspec — which
    `project-structure-and-packages` rule 5 calls the audit artifact anyway. In a
    single-package checkout the kinds are `direct` and `dev`, the shape
    `audit_deps.py` reads. Epic Risk 5 is exactly this: the schema is not ours.
    """
    packages = doc["packages"]
    deps = {p["name"]: list(p.get("dependencies") or []) for p in packages}
    kinds = {p["name"]: p.get("kind") for p in packages}

    parents: dict[str, set[str]] = {}
    for name, children in deps.items():
        for c in children:
            parents.setdefault(c, set()).add(name)

    direct_lines: list[str] = []
    ship_seeds: set[str] = set()
    dev_seeds: set[str] = set()

    if any(k in ("direct", "dev") for k in kinds.values()):
        member = doc.get("root") or "root"
        for p in packages:
            if p["kind"] == "direct":
                direct_lines.append(f"{member} dependencies {p['name']}")
                ship_seeds.add(p["name"])
            elif p["kind"] == "dev":
                direct_lines.append(f"{member} dev_dependencies {p['name']}")
                dev_seeds.add(p["name"])
    else:
        dirs = member_dirs(workspace_root)
        for p in packages:
            if p.get("kind") != "root":
                continue
            d = dirs.get(p["name"])
            if d is None:
                continue  # the workspace root itself ships nothing
            # The RESOLVED GRAPH decides which packages are direct; the member's
            # pubspec only supplies the section label, because the workspace
            # shape merges dependencies and dev_dependencies into one list.
            # Reading membership from the pubspec instead would make this gate
            # unable to see anything the graph says that the manifest does not.
            sections = sections_from_pubspec(workspace_root, d)
            dev = set(sections["dev_dependencies"]) - set(sections["dependencies"])
            for pkg in sorted(set(deps.get(p["name"], []))):
                if pkg in dev:
                    direct_lines.append(f"{d} dev_dependencies {pkg}")
                    dev_seeds.add(pkg)
                else:
                    direct_lines.append(f"{d} dependencies {pkg}")
                    ship_seeds.add(pkg)

    ships = closure(ship_seeds, deps)
    dev_only = closure(dev_seeds, deps) - ships
    return sorted(set(direct_lines)), ships, dev_only, parents


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--deps", help="path to `dart pub deps --json` output; stdin if omitted")
    ap.add_argument("--allowlist-dir", default="tools/gates/allowlist")
    ap.add_argument("--workspace-root", default=".")
    ap.add_argument("--write", action="store_true", help="regenerate the allowlist files")
    args = ap.parse_args()

    doc = load_deps(args.deps)
    direct_lines, ships, dev_only, parents = analyse(doc, args.workspace_root)

    direct_path = os.path.join(args.allowlist_dir, "direct_dependencies.txt")
    edges_path = os.path.join(args.allowlist_dir, "transitive_edges.txt")

    if args.write:
        os.makedirs(args.allowlist_dir, exist_ok=True)
        with open(direct_path, "w", encoding="utf-8") as fh:
            fh.write(DIRECT_HEADER + "\n".join(direct_lines) + "\n")
        if not os.path.exists(edges_path):
            with open(edges_path, "w", encoding="utf-8") as fh:
                fh.write(EDGES_HEADER + "\n".join(
                    f"{p} <- {q}" for p, q in
                    [("http", "flutter_svg"), ("http", "printing"),
                     ("url_launcher_platform_interface", "share_plus")]) + "\n")
        print(f"wrote {len(direct_lines)} direct entries to {direct_path}")
        return 0

    recorded_direct = read_allowlist(direct_path)
    if not recorded_direct:
        print("FAIL: the allowlist is empty — this gate would pass over anything.")
        print(f"      expected entries in {direct_path}")
        print("      regenerate with: dart pub deps --json | "
              "tools/gates/check_dependency_allowlist.py --write")
        return 1

    failed = False

    added = [ln for ln in direct_lines if ln not in recorded_direct]
    removed = [ln for ln in recorded_direct if ln not in direct_lines]
    if added or removed:
        failed = True
        print("FAIL: the resolved graph and the allowlist disagree.")
        for ln in added:
            print(f"  + {ln}    (in the graph, not in the allowlist — nobody reviewed this)")
        for ln in removed:
            print(f"  - {ln}    (in the allowlist, not in the graph — the allowlist "
                  f"no longer describes the app)")

    # SPEC §14: a DIRECT http is a failure in its own right, stated separately so
    # the message names the contract rather than only the diff.
    for ln in direct_lines:
        member, section, pkg = ln.split(" ", 2)
        if pkg in ALWAYS_WATCHED and section == "dependencies":
            failed = True
            print(f"FAIL: {pkg} is a DIRECT dependency of {member}. SPEC.md §14 permits "
                  f"it only as a transitive edge from a named parent.")

    recorded_edges: dict[str, set[str]] = {}
    for ln in read_allowlist(edges_path):
        if "<-" not in ln:
            continue
        pkg, parent = (s.strip() for s in ln.split("<-", 1))
        recorded_edges.setdefault(pkg, set()).add(parent)

    for pkg in sorted(set(ALWAYS_WATCHED) | set(recorded_edges)):
        if pkg not in ships:
            continue
        actual = parents.get(pkg, set()) & ships
        expected = recorded_edges.get(pkg, set())
        if actual != expected:
            failed = True
            print(f"FAIL: {pkg} does not have the parents SPEC.md §14 records.")
            for p in sorted(actual - expected):
                print(f"  + reached from {p!r}, which is not an allowlisted parent")
            for p in sorted(expected - actual):
                print(f"  - allowlisted parent {p!r} no longer reaches it")

    dev_watched = sorted(p for p in set(ALWAYS_WATCHED) | set(recorded_edges)
                         if p in dev_only)
    if dev_watched:
        print("note: reachable only through dev_dependencies, which never ships: "
              + ", ".join(dev_watched))

    if failed:
        return 1
    print(f"check_dependency_allowlist: OK "
          f"({len(recorded_direct)} direct entries, {len(ships)} packages ship)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
