import 'package:content_builder/src/diff/snapshot.dart';
import 'package:meta/meta.dart';

/// What happened to one row between two snapshots.
enum ChangeKind {
  /// The row did not exist before.
  added('added'),

  /// The row exists in both and one of its shipping fields moved.
  amended('amended'),

  /// The row is gone. The change least likely to be noticed in review.
  withdrawn('withdrawn');

  const ChangeKind(this.label);

  /// The word the changelog prints.
  final String label;
}

/// One row's change, with old and new values.
///
/// `licence-provenance.md` requires old → new, because "it changed" answers
/// none of the questions the changelog exists for.
@immutable
class ChangeEntry {
  /// A [kind] change to [section]/[id].
  const ChangeEntry({
    required this.kind,
    required this.section,
    required this.id,
    this.fields = const <String, ({Object? from, Object? to})>{},
  });

  /// Added, amended or withdrawn.
  final ChangeKind kind;

  /// The authoring section, e.g. `rules`.
  final String section;

  /// The authored row id.
  final String id;

  /// The fields that moved, old → new. Empty for an addition or a withdrawal.
  final Map<String, ({Object? from, Object? to})> fields;

  /// One markdown line.
  String render() {
    if (fields.isEmpty) return '- **${kind.label}** `$section/$id`';
    final moved = <String>[
      for (final MapEntry<String, ({Object? from, Object? to})> f in fields.entries)
        '`${f.key}` ${_show(f.value.from)} → ${_show(f.value.to)}',
    ];
    return '- **${kind.label}** `$section/$id`: ${moved.join('; ')}';
  }

  static String _show(Object? value) => value == null ? '_(none)_' : '`$value`';

  @override
  String toString() => render();
}

/// The diff between two snapshots of one jurisdiction.
@immutable
class ContentDiff {
  /// A diff carrying [entries], in `<section>/<id>` order.
  const ContentDiff({
    required this.jurisdiction,
    required this.fromVersion,
    required this.toVersion,
    required this.entries,
  });

  /// The changes between [before] and [after].
  factory ContentDiff.between(Snapshot before, Snapshot after) {
    final entries = <ChangeEntry>[];
    final List<String> keys = <String>{...before.rows.keys, ...after.rows.keys}.toList()..sort();

    for (final key in keys) {
      final Map<String, Object?>? old = before.rows[key];
      final Map<String, Object?>? now = after.rows[key];
      final int slash = key.indexOf('/');
      final String section = key.substring(0, slash);
      final String id = key.substring(slash + 1);

      if (old == null) {
        entries.add(ChangeEntry(kind: ChangeKind.added, section: section, id: id));
        continue;
      }
      if (now == null) {
        entries.add(ChangeEntry(kind: ChangeKind.withdrawn, section: section, id: id));
        continue;
      }

      final moved = <String, ({Object? from, Object? to})>{};
      final List<String> fields = <String>{...old.keys, ...now.keys}.toList()..sort();
      for (final field in fields) {
        if (old[field] != now[field]) moved[field] = (from: old[field], to: now[field]);
      }
      if (moved.isNotEmpty) {
        entries.add(ChangeEntry(kind: ChangeKind.amended, section: section, id: id, fields: moved));
      }
    }

    return ContentDiff(
      jurisdiction: after.jurisdiction,
      fromVersion: before.contentVersion,
      toVersion: after.contentVersion,
      entries: entries,
    );
  }

  /// The jurisdiction directory.
  final String jurisdiction;

  /// `content_version` of the committed snapshot.
  final String fromVersion;

  /// `content_version` of the corpus.
  final String toVersion;

  /// Every change, sorted.
  final List<ChangeEntry> entries;

  /// Whether anything shipped changed.
  bool get isEmpty => entries.isEmpty;

  /// The authored ids this diff touches, whatever section they are in.
  Set<String> get touchedIds => <String>{for (final ChangeEntry e in entries) e.id};

  /// `content/CHANGELOG/<jurisdiction>.md`.
  ///
  /// A repository artefact, not a shipped one: `licence-provenance.md` names its
  /// readers as a regulator, a translator, and a future maintainer answering
  /// "when did this minimum change, and on whose authority". It carries no A2
  /// obligation, which is what stops somebody translating a diff into Catalan.
  /// What ships is the `content_change` row and its keyed strings.
  String renderMarkdown() {
    final buffer = StringBuffer()
      ..writeln('# $jurisdiction — content changelog')
      ..writeln()
      ..writeln('Generated by `dart run content_builder:build`. Do not edit by hand.')
      ..writeln()
      ..writeln(
        'A repository artefact for a regulator, a translator or a future maintainer answering '
        '"when did this minimum change, and on whose authority". It is not shipped and is not '
        'translated; what ships is the `content_change` row and its keyed strings.',
      )
      ..writeln();

    if (entries.isEmpty) {
      buffer.writeln('No shipping rows changed since the committed snapshot.');
      return buffer.toString();
    }

    buffer
      ..writeln('## ${fromVersion.isEmpty ? '(first build)' : fromVersion} → $toVersion')
      ..writeln();
    for (final ChangeEntry entry in entries) {
      buffer.writeln(entry.render());
    }
    return buffer.toString();
  }
}
