import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:content_builder/src/cli/options.dart';
import 'package:content_builder/src/emit/schema.dart';
import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;

/// Emits the two artefacts the app's extraction gate needs.
///
/// **Two artefacts, deliberately.**
///
/// The generated Dart constant is what the gate compares: compiled into the
/// binary, zero I/O, and structurally incapable of disagreeing with the payload
/// that shipped alongside it. The JSON sidecar is what the installer reads for
/// the byte count that drives the determinate bar, and what E18's "about the
/// rule book" screen reads for the counts.
///
/// Neither should require opening ten megabytes of SQLite. `SPEC.md` §7.4
/// records the first draft's circular gate: to read the build date out of the
/// shipped database you must open it, and to open it you must decompress the
/// whole thing to disk — which is the entire job the check was supposed to skip.
///
/// Adding a field to the sidecar is a sidecar change; adding a field the **gate**
/// depends on is a change to `content_build.g.dart`.
void emitContentBuild(ContentBuildOptions options) {
  final Uint8List bytes = options.outFile.readAsBytesSync();
  final digest = '${sha256.convert(bytes)}';
  final String buildDate = _iso(options.buildDate);

  contentBuildJson(options)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(
      '${const JsonEncoder.withIndent('  ').convert(<String, Object?>{'build_date': buildDate, 'schema_version': int.parse(kSchemaVersion), 'bytes': bytes.length, 'sha256': digest})}\n',
    );

  contentBuildDart(options)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(_dart(buildDate, bytes.length, digest));
}

/// `app/assets/content_build.json`.
File contentBuildJson(ContentBuildOptions options) =>
    File(p.join(options.assetsRoot.path, 'content_build.json'));

/// `app/lib/data/services/reference/content_build.g.dart`.
///
/// Derived from the assets root — `app/assets` — so one `--out` fixes every
/// path this build writes and two options cannot disagree about which app they
/// are building for.
File contentBuildDart(ContentBuildOptions options) => File(
  p.join(
    p.dirname(options.assetsRoot.path),
    'lib',
    'data',
    'services',
    'reference',
    'content_build.g.dart',
  ),
);

String _dart(String buildDate, int bytes, String sha256) =>
    '''
// GENERATED BY `dart run content_builder:build`. DO NOT EDIT.
//
// The extraction gate compares [kContentBuildDate] against
// `app_meta.content_build_date` in `user.db`. Both are already in hand: this
// one is compiled into the binary, and that one is a single indexed row in a
// file every screen opens anyway.
//
// SPEC.md §7.4 records why the obvious alternative is wrong. Reading the build
// date out of the shipped database means opening it, which means decompressing
// ten megabytes to disk — the entire job the check exists to skip. The naive
// design therefore re-extracts on every launch, and pays the worst possible
// cost: every time, on the cold-start path, for a comparison of twenty bytes.
library;

/// `content_meta.build_date` of the payload this binary ships with.
const String kContentBuildDate = '$buildDate';

/// `SPEC.md` §7.1's schema version, as the builder wrote it.
const int kContentSchemaVersion = $kSchemaVersion;

/// The UNCOMPRESSED byte count. The determinate progress bar's denominator.
const int kContentBuildBytes = $bytes;

/// The UNCOMPRESSED sha256, verified after decompression and before the rename.
const String kContentBuildSha256 = '$sha256';
''';

String _iso(DateTime date) =>
    '${date.year.toString().padLeft(4, '0')}-'
    '${date.month.toString().padLeft(2, '0')}-'
    '${date.day.toString().padLeft(2, '0')}';
